### ISSUE TITLE
New versions of WLAN/BT drivers from Lenovo

### ISSUE THREAD

**Issue by fpletz** [samcv/A485-RTL8822BE-firmware#1]
The WLAN and Bluetooth drivers have been updated today (2018-10-18) by Lenovo. IMHO tt would make sense to check if the firmware has been altered.

* WLAN firmware version: 2024.0.3.102
  * https://support.lenovo.com/de/en/downloads/ds504117
* BT firmware version: 1.5.1012.3
  * https://support.lenovo.com/de/en/downloads/ds504118

**Comment by samcv** [comment]
Looks like the Bluetooth firmware was unchanged even though Lenovo changed their version.

The Wifi on the otherhand has been bumped to from 20.4.0 to 27.2.0 though. I am attaching the updated wifi firmware, and will update the repo once I've tested it for a few days (since there don't seem any serious issues with the current posted firmware). I am attaching the changed wifi firmware to this post so you and others can test it if needed.

The Bluetooth needing a resume from suspend to become active remains the same.

[rtl8822befw.zip](https://github.com/samcv/A485-RTL8822BE-firmware/files/2497751/rtl8822befw.zip)

**Comment by samcv** [comment]
I've updated the firmware since there don't seem to be any issues with it. Going to close this ticket now.

**Comment by fpletz** [comment]
Thank you very much!
